Added Terraform validation job

diff --git a/.github/workflows/action-terraform-verify.yml b/.github/workflows/action-terraform-verify.yml
--- a/.github/workflows/action-terraform-verify.yml
+++ b/.github/workflows/action-terraform-verify.yml
@@ -1,31 +1,52 @@
-name: Terraform Validation
-
+name: Validate terraform fmt
 on:
-  push:
-    branches:
-      - main
   pull_request:
     branches:
       - main
+      - master
+
+permissions:
+  id-token: write
+  contents: read
 
 jobs:
-  terraform-validate:
-    name: Validate Terraform
+  validate:
     runs-on: ubuntu-latest
+    name: terraform fmt check
+    outputs:
+      CHECK_STATUS: "${{ env.CHECK_STATUS }}"
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Setup Terraform
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 2
+      - name: Fetch changed files
+        id: pr_files
+        uses: jitterbit/get-changed-files@v1
+        with:
+          format: "space-delimited"
+      - name: Configure terraform
         uses: hashicorp/setup-terraform@v2
         with:
-          terraform_version: 1.10.5 
+          terraform_version: 1.2.4
+      - name: Validate terraform fmt (added_modified)
+        run: |
+          set +e
 
-      - name: Initialize Terraform
-        run: terraform init
+          echo "CHECK_STATUS=0" >> $GITHUB_ENV
 
-      - name: Validate Terraform configuration
-        run: terraform validate
+          for changed_file in ${{ steps.pr_files.outputs.added_modified }}; do
+            echo "Checking terraform fmt on ${changed_file}..."
 
-      - name: Check Terraform formatting
-        run: terraform fmt -check
+            if [[ $changed_file == *.tf ]]; then
+              terraform fmt -check $changed_file
+              FMT_STATUS=$(echo $?)
+
+              if [[ $FMT_STATUS -ne 0 ]]; then
+                echo "❌ terraform fmt failed - ${changed_file}" >> $GITHUB_STEP_SUMMARY
+                echo "CHECK_STATUS=1" >> $GITHUB_ENV
+              fi
+            fi
+          done
+      - name: Process check
+        if: always()
+        run: exit $CHECK_STATUS
